name: autolife
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

#  Bloc
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  #screen_utils
  flutter_screenutil: ^5.9.3

  #maks_edit_txt
  mask_text_input_formatter: ^2.9.0

  #intl
  intl: ^0.20.2

flutter:

  uses-material-design: true

  #fonts:
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/exo2_medium.ttf
          weight: 500

  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

